name: capstone-project
on:
  push:
    branches:
      - 'test-action'
jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps: 
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: test-action
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build without push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          load: true
          tags: capstone-devtools:latest
      - 
        name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: capstone-devtools:latest
          args: --severity-threshold=high
      -
        name: Build and push
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/capstone-devtools:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build-scan-push]
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v2
  #     - 
  #       name: Heroku deploy
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: endy-capstone-devtools
  #         heroku_email: ${{ secrets.HEROKU_EMAIL }}