name: week-3-assignment
on:
  push:
    branches:
      - 'master'
jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
      - 
        name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}