name: week-3-assignment
on:
  push:
    branches:
      - 'master'
jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps: 
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build without push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          tags: week3-devtools:latest
      - 
        name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: week3-devtools:latest
          args: --severity-threshold=high

  push-image:
    runs-on: ubuntu-latest
    needs: [build-scan]
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: week3-devtools:latest

