name: week-3-assignment
on:
  push:
    branches:
      - 'master'
jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps: 
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build without push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          tags: week3-devtools:latest
      - 
        name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: week3-devtools:latest
          args: --severity-threshold=high

